name: Tag Version

on:
  push:
    branches:
      - fetch

jobs:
  tag:
    uses: fetch-rewards/common-workflows/.github/workflows/increment-semantic-version.yml@main
    with:
      version-type: patch
      use-app-token: true # Required to trigger the release workflow
    secrets: inherit
